# Generated by Django 5.0.6 on 2024-08-07 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0002_casestatetype"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CASE", "CASE"),
                            ("CASE_CLOSE", "CASE_CLOSE"),
                            ("GENERIC_TASK", "GENERIC_TASK"),
                        ],
                        max_length=250,
                    ),
                ),
                ("emitter_id", models.PositiveIntegerField()),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="cases.case",
                    ),
                ),
                (
                    "emitter_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["date_created"],
            },
        ),
    ]
