# Generated by Django 5.0.8 on 2024-10-31 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caseevent",
            options={"ordering": ["created"]},
        ),
        migrations.RenameField(
            model_name="caseevent",
            old_name="date_created",
            new_name="created",
        ),
    ]
