# Generated by Django 5.0.11 on 2025-03-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_caseevent_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caseevent",
            options={"ordering": ["created"], "verbose_name": "Event"},
        ),
    ]
