# Generated by Django 5.0.8 on 2025-02-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_caseevent_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("CASE", "CASE"),
                    ("CASE_CLOSE", "CASE_CLOSE"),
                    ("GENERIC_TASK", "GENERIC_TASK"),
                    ("CASE_DOCUMENT", "CASE_DOCUMENT"),
                    ("CASE_DOCUMENT_DELETED", "CASE_DOCUMENT_DELETED"),
                ],
                max_length=250,
            ),
        ),
    ]
