services:
  zwd-backend:
    build: app
    hostname: zwd-backend
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-salmagundi/zwd-backend}:${VERSION:-latest}
    ports:
      - 8081:8000
    networks:
      - zwd_network
    command: bash -c "/app/deploy/docker-entrypoint.sh && exec python -m manage runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true

  zwd_celery_worker:
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-salmagundi/zwd-backend}:${VERSION:-latest}
    container_name: zwd_celery_worker
    hostname: zwd_celery_worker
    command: bash -c '/app/celery.sh'
    depends_on:
      - zwd-backend
    networks:
      - zwd_network
    restart: on-failure

networks:
  zwd_network:
    external: true
 

