services:

  zwd-backend:
    build: app
    hostname: zwd-backend
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-salmagundi/zwd-backend}:${VERSION:-latest}
    ports:
      - 8081:8000
      - 5679:5678
    networks:
      - zwd_network
    depends_on:
      - database
    env_file:
      - path: .env
      - path: .env.local
        required: false
      - path: .local.env
        required: false
    command: bash -c "/app/deploy/docker-entrypoint.sh && exec python -m debugpy --listen 0.0.0.0:5678 ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true

  database:
    networks:
      - zwd_network
    image: postgres:15.7
    command: -c 'max_connections=500'
    shm_size: "512m"
    ports:
      - "6410:5432"
    env_file:
      - .env
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  zwd-redis:
    build: redis
    environment:
      - REDIS_PASSWORD=password
      - REDIS_MAXMEM=100mb
    networks:
      - zwd_network
    ports:
      - "6378:6379"

  zwd_celery_worker:
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-salmagundi/zwd-backend}:${VERSION:-latest}
    container_name: zwd_celery_worker
    hostname: zwd_celery_worker
    command: bash -c '/app/celery.sh'
    volumes:
      - ./app:/app
    depends_on:
      - zwd-backend
      - database
      - zwd-redis
    env_file:
      - .env
    networks:
      - zwd_network
    restart: on-failure

  zwd_celery_beat:
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-salmagundi/zwd-backend}:${VERSION:-latest}
    container_name: zwd_celery_beat
    hostname: zwd_celery_beat
    command: bash -c 'watchmedo auto-restart --directory=./ --pattern="*.py;*.bpmn" --recursive -- celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler'
    volumes:
      - ./app:/app
    depends_on:
      - zwd-backend
      - database
      - zwd-redis
    env_file:
      - .env
    networks:
      - zwd_network
    restart: on-failure

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
    networks:
      - zwd_network
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --skipApiVersionCheck

networks:
  zwd_network:
    external: true

volumes:
  postgresql-data:
