# Generated by Django 5.0.11 on 2025-03-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advisor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advisor",
            options={"ordering": ["name"]},
        ),
    ]
