# Generated by Django 5.0.8 on 2024-10-30 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeownerassociation", "0002_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("number_of_appartments", models.IntegerField()),
                (
                    "homeowner_association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="owners",
                        to="homeownerassociation.homeownerassociation",
                    ),
                ),
            ],
        ),
    ]
