# Generated by Django 5.0.8 on 2024-10-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeownerassociation", "0003_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
