# Generated by Django 5.0.8 on 2024-10-31 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeownerassociation", "0005_rename_created_at_homeownerassociation_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name="homeownerassociation",
            old_name="updated_at",
            new_name="updated",
        ),
        migrations.AddField(
            model_name="homeownerassociation",
            name="district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="homeowner_associations",
                to="homeownerassociation.district",
            ),
        ),
    ]
