# Generated by Django 5.0.8 on 2024-10-31 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeownerassociation", "0007_neighborhood"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeownerassociation",
            name="neighborhood",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="homeowner_associations",
                to="homeownerassociation.neighborhood",
            ),
        ),
    ]
