# Generated by Django 5.0.8 on 2024-10-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeownerassociation", "0008_homeownerassociation_neighborhood"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeownerassociation",
            name="zip_code",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
