# Generated by Django 5.0.11 on 2025-02-15 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeownerassociation", "0009_homeownerassociation_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeownerassociation",
            name="beschermd_stadsdorpsgezicht",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="homeownerassociation",
            name="ligt_in_beschermd_gebied",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="homeownerassociation",
            name="monument_status",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Wijk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "neighborhood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wijken",
                        to="homeownerassociation.neighborhood",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="homeownerassociation",
            name="wijk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="homeowner_associations",
                to="homeownerassociation.wijk",
            ),
        ),
    ]
