# Generated by Django 5.0.8 on 2025-02-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homeownerassociation", "0010_added_wijk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wijk",
            options={"verbose_name": "Wijk", "verbose_name_plural": "Wijken"},
        ),
    ]
