# Generated by Django 5.0.11 on 2025-07-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "homeownerassociation",
            "0013_alter_contact_options_alter_district_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="homeownerassociation",
            name="kvk_nummer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
