# Generated by Django 5.0.11 on 2025-07-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homeownerassociation", "0014_add_kvk_nummer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homeownerassociation",
            old_name="number_of_appartments",
            new_name="number_of_apartments",
        ),
        migrations.RenameField(
            model_name="owner",
            old_name="number_of_appartments",
            new_name="number_of_apartments",
        ),
    ]
