# Generated by Django 5.0.11 on 2025-10-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "homeownerassociation",
            "0015_rename_number_of_appartments_homeownerassociation_number_of_apartments_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="homeownerassociation",
            name="annotation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
