# Generated by Django 5.2.8 on 2025-11-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeownerassociation", "0017_add_hoa_communication_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
