# Generated by Django 5.2.8 on 2025-11-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeownerassociation", "0019_add_is_imported_to_communication_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="course_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
