# Generated by Django 5.2.8 on 2025-12-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeownerassociation", "0020_contact_course_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
