# Generated by Django 4.2.16 on 2026-04-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeownerassociation", "0021_contact_is_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="neighborhood",
            name="priority_neighborhood",
            field=models.BooleanField(default=False),
        ),
    ]
