# Generated by Django 4.2.16 on 2026-04-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homeownerassociation", "0022_neighborhood_priority_neighborhood"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PriorityZipCode",
        ),
    ]
