# Generated by Django 5.2.15 on 2026-10-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeownerassociation", "0023_delete_priorityzipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeownerassociation",
            name="beschermd_stadsdorpsgezicht",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="homeownerassociation",
            name="ligt_in_beschermd_gebied",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="homeownerassociation",
            name="monument_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
