# Generated by Django 5.0.6 on 2024-07-17 10:16

import django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseworkflow",
            name="workflow_message_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="caseworkflow",
            name="workflow_theme_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="caseworkflow",
            name="workflow_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="caseworkflow",
            name="workflow_version",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="caseworkflow",
            name="data",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="caseworkflow",
            name="main_workflow",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="caseworkflow",
            name="serialized_workflow_state",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="caseworkflow",
            name="started",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CaseUserTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("task_id", models.UUIDField(unique=True)),
                ("task_name", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("form", models.JSONField(blank=True, default=list, null=True)),
                (
                    "roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("due_date", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="cases.case",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="workflow.caseworkflow",
                    ),
                ),
            ],
        ),
    ]
