# Generated by Django 5.0.6 on 2024-07-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseworkflow',
            name='workflow_message_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caseworkflow',
            name='workflow_theme_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caseworkflow',
            name='workflow_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caseworkflow',
            name='workflow_version',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
