# Generated by Django 5.0.6 on 2024-07-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_caseworkflow_workflow_message_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseworkflow',
            name='case_state_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
