# Generated by Django 5.0.6 on 2024-07-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_caseworkflow_case_state_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseworkflow',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
