# Generated by Django 5.0.6 on 2024-07-26 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_casestatetype"),
        ("workflow", "0004_genericcompletedtask_case_user_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseworkflow",
            name="case_state_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows",
                to="cases.casestatetype",
            ),
        ),
    ]
