# Generated by Django 5.0.6 on 2024-07-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_caseusertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseworkflow',
            name='main_workflow',
            field=models.BooleanField(default=False),
        ),
    ]
