# Generated by Django 5.0.8 on 2025-01-30 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0007_workflowoption"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="caseusertask",
            name="initiated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="case_user_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="caseusertask",
            name="requires_review",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether this task requires review by another user.",
            ),
        ),
    ]
