# Generated by Django 5.0.8 on 2025-01-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0007_workflowoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseworkflow",
            name="previous_data",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="caseworkflow",
            name="previous_serialized_workflow_state",
            field=models.JSONField(null=True),
        ),
    ]
