# Generated by Django 5.0.11 on 2025-03-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0008_caseusertask_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowoption",
            name="enabled_on_case_closed",
            field=models.BooleanField(default=False),
        ),
    ]
