# Generated by Django 5.0.11 on 2025-03-28 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0010_remove_caseworkflow_case_state_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseworkflow",
            name="parent_workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_workflows",
                to="workflow.caseworkflow",
            ),
        ),
    ]
