# Generated by Django 4.2.16 on 2025-12-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0011_caseworkflow_parent_workflow"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseWorkflowStateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serialized_workflow_state", models.JSONField()),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_history",
                        to="workflow.caseworkflow",
                    ),
                ),
            ],
        ),
    ]
