# Generated by Django 4.2.16 on 2026-01-27 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0012_caseworkflowstatehistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caseworkflowstatehistory",
            options={"verbose_name_plural": "Case workflow state histories"},
        ),
    ]
