# Generated by Django 5.0.8 on 2024-10-14 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_casestatetype"),
        ("homeownerassociation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="advice_type",
            field=models.CharField(
                choices=[
                    ("Energieadvies", "ENERGY_ADVICE"),
                    ("Haalbaarheidsonderzoek", "HBO"),
                    ("Cursus", "COURSE"),
                ],
                default="Cursus",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="homeowner_association",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases",
                to="homeownerassociation.homeownerassociation",
                null=True,
            ),
            preserve_default=False,
        ),
    ]
