# Generated by Django 5.0.8 on 2024-10-17 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_case_advice_type_case_homeowner_association"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="case",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
