# Generated by Django 5.0.8 on 2024-10-31 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_casedocument"),
    ]

    operations = [
        migrations.RenameField(
            model_name="casedocument",
            old_name="created_at",
            new_name="created",
        ),
    ]
