# Generated by Django 5.0.11 on 2025-02-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0007_case_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
