# Generated by Django 5.0.8 on 2025-02-20 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advisor", "0003_remove_advisor_advice_types_and_more"),
        ("cases", "0008_update_description_field_cases_to_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="advisor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="case_advisor",
                to="advisor.advisor",
            ),
        ),
    ]
