# Generated by Django 5.0.8 on 2025-02-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_casedocument_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="casedocument",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
