# Generated by Django 5.0.11 on 2025-03-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0009_case_advisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="legacy_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
