# Generated by Django 5.0.11 on 2025-03-18 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advisor", "0001_initial"),
        ("cases", "0010_case_legacy_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="advisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="case_advisor",
                to="advisor.advisor",
            ),
        ),
        migrations.AlterField(
            model_name="casedocument",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="cases.case",
            ),
        ),
    ]
