# Generated by Django 5.0.11 on 2025-03-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0010_case_legacy_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
