# Generated by Django 5.0.11 on 2025-03-24 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_alter_case_advisor_alter_casedocument_case"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="casedocument",
            options={"verbose_name": "Document"},
        ),
        migrations.AlterModelOptions(
            name="casestatetype",
            options={
                "ordering": ["name"],
                "verbose_name": "Status",
                "verbose_name_plural": "Statuses",
            },
        ),
        migrations.AddField(
            model_name="case",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases_status",
                to="cases.casestatetype",
            ),
        ),
    ]
