# Generated by Django 5.0.11 on 2025-03-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0012_alter_case_options_alter_casedocument_options_and_more"),
        ("workflow", "0005_caseworkflow_case_state_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CaseStateType",
            new_name="CaseStatus",
        ),
    ]
