# Generated by Django 5.0.11 on 2025-03-20 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0012_case_end_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="casedocument",
            options={"verbose_name": "Document"},
        ),
        migrations.AlterModelOptions(
            name="casestatetype",
            options={
                "ordering": ["name"],
                "verbose_name": "Status",
                "verbose_name_plural": "Statuses",
            },
        ),
        migrations.AddField(
            model_name="case",
            name="case_state_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases_state_type",
                to="cases.casestatetype",
            ),
        ),
    ]
