# Generated by Django 5.0.11 on 2025-06-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_rename_casestatetype_casestatus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casestatus",
            options={
                "ordering": ["position"],
                "verbose_name": "Status",
                "verbose_name_plural": "Statuses",
            },
        ),
        migrations.AddField(
            model_name="casestatus",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
