# Generated by Django 5.0.11 on 2025-03-20 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_alter_case_options_alter_casedocument_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CaseStateType",
            new_name="CaseStatus",
        ),
        migrations.RemoveField(
            model_name="case",
            name="case_state_type",
        ),
        migrations.AddField(
            model_name="case",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cases_status",
                to="cases.casestatus",
            ),
        ),
    ]
