# Generated by Django 5.0.11 on 2025-06-19 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0014_alter_casestatus_options_casestatus_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="application_type",
            field=models.CharField(
                choices=[("Advies", "ADVICE"), ("Activatieteam", "ACTIVATIONTEAM")],
                default="Advies",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="advice_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Energieadvies", "ENERGY_ADVICE"),
                    ("Haalbaarheidsonderzoek", "HBO"),
                    ("Cursus", "COURSE"),
                ],
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ActivationTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Informatiebijeenkomst", "INFORMATIEBIJEENKOMST"),
                            ("Ledenvergadering", "LEDENVERGADERING"),
                        ],
                        default="Informatiebijeenkomst",
                    ),
                ),
                ("subject", models.TextField(blank=True, null=True)),
                ("meeting_date", models.DateField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activation_team",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activatieteam",
            },
        ),
    ]
