# Generated by Django 5.2.5 on 2025-09-15 13:31

from django.db import migrations, models
from django.utils import timezone


def backfill_request_date_from_created(apps, schema_editor):
    Case = apps.get_model("cases", "Case")
    from django.db.models.functions import TruncDate

    # Fill request_date with the date component of created where it's currently null
    Case.objects.filter(request_date__isnull=True).update(
        request_date=TruncDate("created")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0019_backfill_prefixed_dossier_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="request_date",
            field=models.DateField(default=timezone.now),
        ),
        migrations.RunPython(
            backfill_request_date_from_created, migrations.RunPython.noop
        ),
    ]
