# Generated by Django 5.2.5 on 2025-09-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0020_case_request_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="communication_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
