# Generated by Django 5.2.5 on 2025-10-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0023_remove_case_communication_note"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CaseCommunicationNote",
        ),
    ]
