# Generated by Django 4.2.16 on 2026-01-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0025_move_course_to_application_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="application_type",
            field=models.CharField(
                choices=[("Advies", "ADVICE"), ("Activatieteam", "ACTIVATIONTEAM")],
                default="Advies",
            ),
        ),
    ]
