# Generated by Django 5.2.12 on 2026-05-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0026_alter_case_application_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="advice_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Energieadvies", "ENERGY_ADVICE"),
                    ("Haalbaarheidsonderzoek", "HBO"),
                    ("Oud advies", "OUD"),
                ],
                null=True,
            ),
        ),
    ]
