# Generated by Django 5.2.12 on 2026-06-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0027_alter_case_advice_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="advice_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Energieadvies", "ENERGY_ADVICE"),
                    ("Haalbaarheidsonderzoek", "HBO"),
                    ("Energieadvies (OUD)", "OLD_ENERGY_ADVICE"),
                    ("Zon-Advies (OUD)", "OLD_SOLAR_ADVICE"),
                ],
                null=True,
            ),
        ),
    ]
